# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='test',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0emessages.proto\x12\x04test\"j\n+CLoyaltyRewards_GetSummary_Response_Summary\x12\x0e\n\x06points\x18\x01 \x02(\x03\x12\x15\n\rpoints_earned\x18\x02 \x02(\x03\x12\x14\n\x0cpoints_spent\x18\x03 \x02(\x03\"\x9f\x01\n#CLoyaltyRewards_GetSummary_Response\x12\x42\n\x07summary\x18\x01 \x02(\x0b\x32\x31.test.CLoyaltyRewards_GetSummary_Response_Summary\x12\x19\n\x11timestamp_updated\x18\x02 \x02(\r\x12\x19\n\x11\x61uditid_highwater\x18\x03 \x02(\x04\"5\n\"CLoyaltyRewards_GetSummary_Request\x12\x0f\n\x07steamid\x18\x01 \x02(\x06\"\xb1\x01\n*CLoyaltyRewards_GetReactionConfig_Response\x12\x13\n\x0bpoints_cost\x18\x01 \x02(\x03\x12\x1a\n\x12points_transferred\x18\x02 \x02(\x03\x12R\n\treactions\x18\x03 \x03(\x0b\x32?.test.CLoyaltyRewards_GetReactionConfig_Response_ReactionConfig\"\xb5\x01\n9CLoyaltyRewards_GetReactionConfig_Response_ReactionConfig\x12\x12\n\nreactionid\x18\x01 \x02(\r\x12\x13\n\x0bpoints_cost\x18\x02 \x02(\r\x12\x1a\n\x12points_transferred\x18\x03 \x02(\x04\x12\x1a\n\x12valid_target_types\x18\x04 \x03(\r\x12\x17\n\x0fvalid_ugc_types\x18\x05 \x03(\r\"<\n%CLoyaltyRewards_GetReactions_Response\x12\x13\n\x0breactionids\x18\x01 \x03(\x03\"M\n$CLoyaltyRewards_GetReactions_Request\x12\x13\n\x0btarget_type\x18\x01 \x02(\x05\x12\x10\n\x08targetid\x18\x02 \x02(\x04\"`\n#CLoyaltyRewards_AddReaction_Request\x12\x13\n\x0btarget_type\x18\x01 \x02(\x05\x12\x10\n\x08targetid\x18\x02 \x02(\x04\x12\x12\n\nreactionid\x18\x03 \x02(\r'
)




_CLOYALTYREWARDS_GETSUMMARY_RESPONSE_SUMMARY = _descriptor.Descriptor(
  name='CLoyaltyRewards_GetSummary_Response_Summary',
  full_name='test.CLoyaltyRewards_GetSummary_Response_Summary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='test.CLoyaltyRewards_GetSummary_Response_Summary.points', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='points_earned', full_name='test.CLoyaltyRewards_GetSummary_Response_Summary.points_earned', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='points_spent', full_name='test.CLoyaltyRewards_GetSummary_Response_Summary.points_spent', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=130,
)


_CLOYALTYREWARDS_GETSUMMARY_RESPONSE = _descriptor.Descriptor(
  name='CLoyaltyRewards_GetSummary_Response',
  full_name='test.CLoyaltyRewards_GetSummary_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='summary', full_name='test.CLoyaltyRewards_GetSummary_Response.summary', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp_updated', full_name='test.CLoyaltyRewards_GetSummary_Response.timestamp_updated', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='auditid_highwater', full_name='test.CLoyaltyRewards_GetSummary_Response.auditid_highwater', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=292,
)


_CLOYALTYREWARDS_GETSUMMARY_REQUEST = _descriptor.Descriptor(
  name='CLoyaltyRewards_GetSummary_Request',
  full_name='test.CLoyaltyRewards_GetSummary_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='steamid', full_name='test.CLoyaltyRewards_GetSummary_Request.steamid', index=0,
      number=1, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=347,
)


_CLOYALTYREWARDS_GETREACTIONCONFIG_RESPONSE = _descriptor.Descriptor(
  name='CLoyaltyRewards_GetReactionConfig_Response',
  full_name='test.CLoyaltyRewards_GetReactionConfig_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='points_cost', full_name='test.CLoyaltyRewards_GetReactionConfig_Response.points_cost', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='points_transferred', full_name='test.CLoyaltyRewards_GetReactionConfig_Response.points_transferred', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reactions', full_name='test.CLoyaltyRewards_GetReactionConfig_Response.reactions', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=527,
)


_CLOYALTYREWARDS_GETREACTIONCONFIG_RESPONSE_REACTIONCONFIG = _descriptor.Descriptor(
  name='CLoyaltyRewards_GetReactionConfig_Response_ReactionConfig',
  full_name='test.CLoyaltyRewards_GetReactionConfig_Response_ReactionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reactionid', full_name='test.CLoyaltyRewards_GetReactionConfig_Response_ReactionConfig.reactionid', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='points_cost', full_name='test.CLoyaltyRewards_GetReactionConfig_Response_ReactionConfig.points_cost', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='points_transferred', full_name='test.CLoyaltyRewards_GetReactionConfig_Response_ReactionConfig.points_transferred', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valid_target_types', full_name='test.CLoyaltyRewards_GetReactionConfig_Response_ReactionConfig.valid_target_types', index=3,
      number=4, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valid_ugc_types', full_name='test.CLoyaltyRewards_GetReactionConfig_Response_ReactionConfig.valid_ugc_types', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=530,
  serialized_end=711,
)


_CLOYALTYREWARDS_GETREACTIONS_RESPONSE = _descriptor.Descriptor(
  name='CLoyaltyRewards_GetReactions_Response',
  full_name='test.CLoyaltyRewards_GetReactions_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reactionids', full_name='test.CLoyaltyRewards_GetReactions_Response.reactionids', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=713,
  serialized_end=773,
)


_CLOYALTYREWARDS_GETREACTIONS_REQUEST = _descriptor.Descriptor(
  name='CLoyaltyRewards_GetReactions_Request',
  full_name='test.CLoyaltyRewards_GetReactions_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_type', full_name='test.CLoyaltyRewards_GetReactions_Request.target_type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='targetid', full_name='test.CLoyaltyRewards_GetReactions_Request.targetid', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=775,
  serialized_end=852,
)


_CLOYALTYREWARDS_ADDREACTION_REQUEST = _descriptor.Descriptor(
  name='CLoyaltyRewards_AddReaction_Request',
  full_name='test.CLoyaltyRewards_AddReaction_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_type', full_name='test.CLoyaltyRewards_AddReaction_Request.target_type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='targetid', full_name='test.CLoyaltyRewards_AddReaction_Request.targetid', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reactionid', full_name='test.CLoyaltyRewards_AddReaction_Request.reactionid', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=854,
  serialized_end=950,
)

_CLOYALTYREWARDS_GETSUMMARY_RESPONSE.fields_by_name['summary'].message_type = _CLOYALTYREWARDS_GETSUMMARY_RESPONSE_SUMMARY
_CLOYALTYREWARDS_GETREACTIONCONFIG_RESPONSE.fields_by_name['reactions'].message_type = _CLOYALTYREWARDS_GETREACTIONCONFIG_RESPONSE_REACTIONCONFIG
DESCRIPTOR.message_types_by_name['CLoyaltyRewards_GetSummary_Response_Summary'] = _CLOYALTYREWARDS_GETSUMMARY_RESPONSE_SUMMARY
DESCRIPTOR.message_types_by_name['CLoyaltyRewards_GetSummary_Response'] = _CLOYALTYREWARDS_GETSUMMARY_RESPONSE
DESCRIPTOR.message_types_by_name['CLoyaltyRewards_GetSummary_Request'] = _CLOYALTYREWARDS_GETSUMMARY_REQUEST
DESCRIPTOR.message_types_by_name['CLoyaltyRewards_GetReactionConfig_Response'] = _CLOYALTYREWARDS_GETREACTIONCONFIG_RESPONSE
DESCRIPTOR.message_types_by_name['CLoyaltyRewards_GetReactionConfig_Response_ReactionConfig'] = _CLOYALTYREWARDS_GETREACTIONCONFIG_RESPONSE_REACTIONCONFIG
DESCRIPTOR.message_types_by_name['CLoyaltyRewards_GetReactions_Response'] = _CLOYALTYREWARDS_GETREACTIONS_RESPONSE
DESCRIPTOR.message_types_by_name['CLoyaltyRewards_GetReactions_Request'] = _CLOYALTYREWARDS_GETREACTIONS_REQUEST
DESCRIPTOR.message_types_by_name['CLoyaltyRewards_AddReaction_Request'] = _CLOYALTYREWARDS_ADDREACTION_REQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CLoyaltyRewards_GetSummary_Response_Summary = _reflection.GeneratedProtocolMessageType('CLoyaltyRewards_GetSummary_Response_Summary', (_message.Message,), {
  'DESCRIPTOR' : _CLOYALTYREWARDS_GETSUMMARY_RESPONSE_SUMMARY,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:test.CLoyaltyRewards_GetSummary_Response_Summary)
  })
_sym_db.RegisterMessage(CLoyaltyRewards_GetSummary_Response_Summary)

CLoyaltyRewards_GetSummary_Response = _reflection.GeneratedProtocolMessageType('CLoyaltyRewards_GetSummary_Response', (_message.Message,), {
  'DESCRIPTOR' : _CLOYALTYREWARDS_GETSUMMARY_RESPONSE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:test.CLoyaltyRewards_GetSummary_Response)
  })
_sym_db.RegisterMessage(CLoyaltyRewards_GetSummary_Response)

CLoyaltyRewards_GetSummary_Request = _reflection.GeneratedProtocolMessageType('CLoyaltyRewards_GetSummary_Request', (_message.Message,), {
  'DESCRIPTOR' : _CLOYALTYREWARDS_GETSUMMARY_REQUEST,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:test.CLoyaltyRewards_GetSummary_Request)
  })
_sym_db.RegisterMessage(CLoyaltyRewards_GetSummary_Request)

CLoyaltyRewards_GetReactionConfig_Response = _reflection.GeneratedProtocolMessageType('CLoyaltyRewards_GetReactionConfig_Response', (_message.Message,), {
  'DESCRIPTOR' : _CLOYALTYREWARDS_GETREACTIONCONFIG_RESPONSE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:test.CLoyaltyRewards_GetReactionConfig_Response)
  })
_sym_db.RegisterMessage(CLoyaltyRewards_GetReactionConfig_Response)

CLoyaltyRewards_GetReactionConfig_Response_ReactionConfig = _reflection.GeneratedProtocolMessageType('CLoyaltyRewards_GetReactionConfig_Response_ReactionConfig', (_message.Message,), {
  'DESCRIPTOR' : _CLOYALTYREWARDS_GETREACTIONCONFIG_RESPONSE_REACTIONCONFIG,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:test.CLoyaltyRewards_GetReactionConfig_Response_ReactionConfig)
  })
_sym_db.RegisterMessage(CLoyaltyRewards_GetReactionConfig_Response_ReactionConfig)

CLoyaltyRewards_GetReactions_Response = _reflection.GeneratedProtocolMessageType('CLoyaltyRewards_GetReactions_Response', (_message.Message,), {
  'DESCRIPTOR' : _CLOYALTYREWARDS_GETREACTIONS_RESPONSE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:test.CLoyaltyRewards_GetReactions_Response)
  })
_sym_db.RegisterMessage(CLoyaltyRewards_GetReactions_Response)

CLoyaltyRewards_GetReactions_Request = _reflection.GeneratedProtocolMessageType('CLoyaltyRewards_GetReactions_Request', (_message.Message,), {
  'DESCRIPTOR' : _CLOYALTYREWARDS_GETREACTIONS_REQUEST,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:test.CLoyaltyRewards_GetReactions_Request)
  })
_sym_db.RegisterMessage(CLoyaltyRewards_GetReactions_Request)

CLoyaltyRewards_AddReaction_Request = _reflection.GeneratedProtocolMessageType('CLoyaltyRewards_AddReaction_Request', (_message.Message,), {
  'DESCRIPTOR' : _CLOYALTYREWARDS_ADDREACTION_REQUEST,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:test.CLoyaltyRewards_AddReaction_Request)
  })
_sym_db.RegisterMessage(CLoyaltyRewards_AddReaction_Request)


# @@protoc_insertion_point(module_scope)
